# Dada la siguiente lista homogenea:
# lista = ["JUAN", "HOLA", "mochila", "SACO", barco""]
# Mostrar el 2 valor por pantalla
# Tener en cuenta, el programacion el primer elementos de una lista es el 0.
# Los programadores no contamos como nos enseñaron en la primaria: 1,2,3,4....
# Sino que contamos: 0,1,2,3....
